import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased min-h-screen w-full bg-background text-foreground`}>
          <div className="
          absolute inset-0 h-full w-full bg-grid bg-size-[14px_24px] pointer-events-none
          [mask-image:radial-gradient(ellipse_at_bottom,transparent_25%,black)]"></div>
        {children}
      </body>
    </html>
  );
}
